# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title create_struct_example
#' @description Create a Simple \sQuote{struct} Object
#' @details A two-column \sQuote{struct} is created and returned, containing respectively an
#' integer and a floating point column each with one missing value
#' @return A external pointer object is returned containing a pointer to the Arrow array with
#' a pointer to the schema tucked away in the \sQuote{tag} component as is common for
#' \pkg{nanoarrow} objects
#' @examples
#' s <- create_struct_example()
#' s                 # pretty-printed in full details thanks to 'nanoarrow' S3 methods
#' as.data.frame(s)  # converted thanks to 'nanoarrow' S3 methods
create_struct_example <- function() {
    .Call(`_acane_create_struct_example`)
}

#' @title Display Arrow Structures Array or Schema
#' @description Helper functions showing elements of \sQuote{Arrow Array} or
#' \sQuote{Arrow Schema} objects provided via an external pointer
#' @param sxparr An external pointer to an \sQuote{Arrow Array} also containing
#' a pointer to the corresponding \sQuote{Arrow Schema} in its \sQuote{tag} slot
#' @return Nothing is returned, the functions are invoked for the side effect
#' of printing
show_array <- function(sxparr) {
    invisible(.Call(`_acane_show_array`, sxparr))
}

#' @rdname show_array
show_schema <- function(sxparr) {
    invisible(.Call(`_acane_show_schema`, sxparr))
}

#' @rdname show_array
#' @param array_xptr A external pointer to an Arrow array data structure
#' @param schema_xptr A external pointer to an Arrow schema data structure
array_xptr_set_schema <- function(array_xptr, schema_xptr) {
    invisible(.Call(`_acane_array_xptr_set_schema`, array_xptr, schema_xptr))
}

#' @rdname show_array
array_xptr_get_schema <- function(array_xptr) {
    .Call(`_acane_array_xptr_get_schema`, array_xptr)
}

